name: get-json-property
description: Get a property from a json file using jq

# Examples:
# prop_path: version
# prop_path: devDependencies["@salesforce/dev-scripts"]


inputs:
  path:
    required: true
    description: Json file to look up prop (package.json)
  prop_path:
    required: true
    description: jq query to search (version)

outputs:
  prop:
    description: The value of the prop_path
    value: ${{ steps.jq.outputs.prop }}

runs:
  using: "composite"
  steps:
    - name: Get property from json file
      id: jq
      shell: bash
      run: |
        PROP=$(jq -r '.${{ inputs.prop_path }}' ${{ inputs.path }})
        if [ -z "$PROP" ]; then
          echo "Property '${{ inputs.prop_path }}' not found in ${{ inputs.path }}"
          exit 1
        fi
        echo "prop=$PROP" >> "$GITHUB_OUTPUT"
