name: automerge-pr

on:
  # TODO: ADD A PR CHECK TOMORROW
  # pull_request:
  #   types: [opened]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    # TODO: Add a label, but call it nightly automerge. Then update our cle:release:build script to add that label
    if: startsWith(github.event.pull_request.title, 'Automerge PR')
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@eb68b061739cb9d81564f8e812d0b3c45f0fb09a"
        env:
          GITHUB_TOKEN: "${{ secrets.TESTINGAUTOMERGETOKEN }}"
          MERGE_LABELS: "test-automerge"
          MERGE_COMMIT_MESSAGE: "pull-request-title" # Use the PR title as the commit message
          MERGE_FILTER_AUTHOR: "iowillhoit" # Only automerge PRs from this author
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "true"
          MERGE_FORKS: "false"
          MERGE_ERROR_FAIL: "true" # Exit 1 for this action if merge fails
          MERGE_RETRIES: "10" # Wait for checks to complete
          MERGE_RETRY_SLEEP: "180000" # 3 minutes (30 minutes total)
          UPDATE_RETRIES: "30"
          UPDATE_RETRY_SLEEP: "60000" # 1 minute
