name: branch-check

on:
  pull_request:
    types: [opened, edited, labeled]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch is: ${{ github.ref }}"
          echo "Branch contains 'foo': ${{ contains('refs/heads/foo', github.ref) }}"
          echo "---"
          echo "HEAD Branch is: ${{ github.head_ref }}"
          echo "Branch contains 'foo': ${{ contains('foo', github.head_ref) }}"
          echp "---"
          echo "event: ${{ toJson(github.event) }}"

          echo "---"
