name: exit-early

on:
  workflow_call:
  
jobs:
  start-log:
    runs-on: ubuntu-latest
    steps:
      run: echo "first job"
      
  exit early:
    runs-on: ubuntu-latest
    steps:
      run: |
        echo "attempting to exit with exitcode 1"
        exit 1
        
  final-log:
    runs-on: ubuntu-latest
    steps:
      run: echo "should not echo"
