name: Dynamically set env vars
on:
  workflow_dispatch:

# all possible combinations of OS and architecture supported by yourkit
env:
  Linux_ARM: ./yourkit-distro/linux-arm-32/libyjpagent.so
  Windows_X86: ./yourkit-distro/windows-x86-32/yjpagent.dll
  Linux_X86: ./yourkit-distro/linux-x86-32/libyjpagent.so
  Windows_X64: ./yourkit-distro/windows-x86-64/yjpagent.dll
  Linux_ARM64: ./yourkit-distro/linux-arm-64/libyjpagent.so
  macOs_X64: ./yourkit-distro/mac/libyjpagent.dylib
  Windows_ARM64: ./yourkit-distro/windows-arm-64/yjpagent.dll
  Linux_X64: ./yourkit-distro/linux-x86-64/libyjpagent.so

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        nodeVersion:
          - 16.15.1
        vscodeVersion:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set envs
        run: echo "YOURKIT_PROFILER_AGENT=${{ env[format('{0}_{1}', runner.os, runner.arch)] }}=sampling,async_sampling_cpu,app_name=apex_lsp,alloc_object_counting,onexit=memory,onexit=memory,onexit=snapshot,onexit=hprof,dir=./snapshots" >> $GITHUB_ENV
      - name: Verify Env
        run: env
