name: git-config-tests
on:
  workflow_dispatch:

jobs:
  git-config-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Log git config
        run: |
          echo "---local---"
          git config --get user.email
          git config --get user.name
          echo "---global---"
          git config --global --get user.email
          git config --global --get user.name
