name: needing-an-optional-job-alternative

on:
  workflow_dispatch:
    inputs:
      run-optional:
        type: boolean
        description: Run the optional job
      fail-optional:
        type: boolean
        description: Simulate a failure on the optional job (for testing)

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "First job complete!"

  # This is an alternate approach for "needing" an optional job.
  # Rather than adding the following to every future job:
  #   if: always() && (needs.optional-job.result == 'success' || needs.optional-job.result == 'skipped')
  # We add a second step that always() checks the status of the optional-step and exit if it fails
  optional-job:
    needs: [first-job]
    runs-on: ubuntu-latest
    steps:
      - id: run-optional-step
        if: inputs.run-optional
        run: |
          echo "Running optional step"
          if [[ ${{ inputs.fail-optional }} == "true" ]]; then
            echo "Optional step failed!"
            exit 1
          fi
      - id: validate-optional-step
        if: always()
        run: |
          RESULT=${{ steps.run-optional-step.outcome }}
          if [[ "$RESULT" != 'success' && "$RESULT" != 'skipped' ]]; then
            exit 1
          else
            echo "Optional job was successful or was skipped, proceeding."
          fi

  # This will run if `optional-job` was successful or skipped
  # This will _not_ run if `optional-job` failed
  depends-on-optional:
    needs: [optional-job]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Optional job passed or was skipped!"

  also-depends-on-optional:
    needs: [optional-job]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Optional job passed or was skipped!"
