#
# Copyright (c) 2021, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
#

name: "new-label"
on: # any labels added to an issue
  issues:
    types: [labeled]

jobs:
  validate-issue:
    if: ${{ github.event.label.name == 'investigating' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Validate issue
        id: validate-issue
        uses: ./.github/actions/validate-issue
        # with:
        # repo-token: ${{ secrets.GITHUB_TOKEN}}
