name: node-version-tests
on:
  workflow_dispatch:

jobs:
  node-version-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}
      - name: Log Node version
        run: |
          node --version
