name: testing-get-json-property
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to checkout'
        required: true
        default: 'salesforcecli/plugin-org'
      path:
        description: 'Json file to look up prop (example: package.json)'
        required: true
        default: 'package.json'
      prop_path:
        description: 'jq query to search (example: version)'
        required: true
        default: 'version'

jobs:
  testing-get-json-property:
    name: Testing get-json-property
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          path: .

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Get json property
        id: get-json-property
        uses: iowillhoit/gha-sandbox/.github/actions/get-json-property@main
        with:
          path: ${{ inputs.path }}
          prop_path: ${{ inputs.prop_path }}

      - name: Echo output
        run: |
          echo "Value of '${{ inputs.prop_path }}' in '${{ inputs.path }}' is '${{ steps.get-json-property.outputs.prop }}'"
