name: testing-inputs
on:
  workflow_dispatch:
    inputs:
      string:
        description: 'String input'
        required: true

jobs:
  testing-inputs:
    name: Testing inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
      - name: printf output
        run: |
          FOO="${{ inputs.string }}"
          printf "Value %s from inputs.string" $FOO
    #   - name: Echo output
    #     run: |
    #       echo 'Value ${{ inputs.string }} from inputs.string'
