name: use-needs-to-skip-all-following-steps

on:
  workflow_dispatch:

jobs:
  start-log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "first job"

  exit-early:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
      - name: install change-case-management
        run: npm install -g @salesforce/change-case-management --omit=dev
      - name: testing exit 1
        shell: bash
        run: |
          echo "before command"
          CTC_RESULT=$(sfchangecase create --location git://github.com/salesforcecli/testPackageRelease.git --release salesforcecli/testPackageRelease.$(date +%F) --json 2>&1)
          echo "before echo"
          echo $CTC_RESULT
          echo "after echo"

          # STATUS=$(printf '%s' "$CTC_RESULT" | jq -r '.status')
          # CTC_ID=$(printf '%s' "$CTC_RESULT" | jq -r '.result.id')

          # if [[ "$STATUS" == "0" && "$CTC_ID" != "null" ]]; then
          #     echo "Successfully created case with ID: $CTC_ID"
          #     echo "ctcId=$CTC_ID" >> "$GITHUB_OUTPUT"
          # else
          #     echo "CTC failed to open a case. Result:"
          #     echo "$CTC_RESULT"
          #     exit 1
          # fi
          echo "attempting to exit with exitcode 1"
          # exit 1

  final-log:
    needs: [exit-early]
    runs-on: ubuntu-latest
    steps:
      - run: echo "should not echo"
