name: verify-docker-cli-versions

on:
  workflow_dispatch:
    inputs:
      channel:
        type: string
        description: Channel to check, latest, latest-rc, nightly, etc
        default: nightly

jobs:
  verify-docker-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get npm version
        id: npm-version
        run: |
          VERSION=$(npm view @salesforce/cli@${{ inputs.channel }} --json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Get docker full CLI version
        id: docker-full-version
        run: |
          docker pull salesforce/cli:${{ inputs.channel }}-full
          VERSION=$(docker run --rm salesforce/cli:${{ inputs.channel }}-full sf version --json | jq -r '.cliVersion' | cut -d'/' -f 3)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Get docker slim CLI version
        id: docker-slim-version
        run: |
          docker pull salesforce/cli:${{ inputs.channel }}-slim
          VERSION=$(docker run --rm salesforce/cli:${{ inputs.channel }}-slim sf version --json | jq -r '.cliVersion' | cut -d'/' -f 3)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Compare Docker versions against npm
        run: |
          echo "NPM ${{ inputs.channel }} version is: ${{ steps.npm-version.outputs.version }}"
          echo "Docker ${{ inputs.channel }}-full version is: ${{ steps.docker-full-version.outputs.version }}"
          echo "Docker ${{ inputs.channel }}-slim version is: ${{ steps.docker-slim-version.outputs.version }}"
          if [ "${{ steps.npm-version.outputs.version }}" == "${{ steps.docker-full-version.outputs.version }}" ] && [ "${{ steps.docker-full-version.outputs.version }}" == "${{ steps.docker-slim-version.outputs.version }}" ]; then
            echo "Docker versions match npm version. Proceeding..."
          else
            echo "Version mismatch! Exiting..."
            exit 1
          fi
